project:
  type: website

website:
  title: "sciences.social"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: status.qmd
        text: Status

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

