---
title: "Policies"
---

### Policies
At the moment, the official rules are deliberately minimal, but they have important implications. First, if you don't understand that "treat people with respect" means no sexism, racism, homophobia, transphobia or casteism and precludes abusive behavior and doxxing, then you don't belong on this site. Second, you must use your real name in your profile and we strongly encourage using your full name as your display name. While there are plenty of good reasons for anonymity on the internet, for our purposes being able to link online reputation to real-world reputation is important.

### Post Visibility

Public posts appear on the local timelines and federated timelines of sciences.social and all other mastodon instances that host your followers. Consider using Unlisted for posts you want your followers to see, but would prefer not to appear in public timelines. **Using Unlisted for replies is strongly encouraged.**

Posts expressing racism, homophobia and the like are not allowed with or without a content warning or with any level of visibility.

### Sensitive Media

You must mark media as sensitive if it contains violence or sexual content. We also request that you mark media as sensitive if it might trigger common phobias including arachnophobia (fear of spiders) and Ophidiophobia (fear of snakes).

### Getting along

Folks come here from different academic, ethnic and national cultures, so there are likely to be some mismatches in tone when we talk to one another. People might be more blunt than you are used to, or you might think someone is frustratingly obtuse when they are just trying to be polite. It's best to presume that folks here are acting in good faith. Mastodon has good tools for filtering or blocking posts you don't want to see. However, if you think someone is deliberately violating the rules or negatively affecting the community as a whole, you can report them as described below.

### Reporting bad behavior

One of the great strengths of Mastodon is the ability to restrict access to bad actors. sciences.social already blocks posts from dozens of sites known to host trolls and nazis, but there'll be other bad behavior. If you use the "Report" action on someone's post the moderators can review it and take action to restrict that account. Reporting helps even for people who make their home on other servers.

### Content Warnings

Content warnings are an important part of both the technical infrastructure and the culture of the Mastodon online community. They aren't just used for "triggering" content but also are often treated as a “headline” that allows people to choose whether they want to read the whole post. Click the CW link on your post to set one.

We strongly encourage the use of content warnings for posts that you think might be triggering or of limited interest, for example mentions of death or violence, and political debates centered on one country or locality.

While expressions of racism, casteism, homophobia, and transphobia are off-limits, we do not require content warnings for posts _about_ those topics and their effects on people, whether academic or otherwise. Use your own judgment about using content warnings on these topics.
